services:
  postgres:
    container_name: postgres_container
    build: ./postgre
    image: postgres
    restart: always
    env_file:      
      - .env
    ports: 
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s 
    command: ["postgres", "-c", "log_statement=all"]
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports: 
      - "16543:80"
    links:
      - "postgres:pgsql-server"